// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type User struct {
	ID        int64
	Name      string
	Dob       time.Time
	CreatedAt sql.NullTime
}
